version: 0.4.0.{build}
max_jobs: 2
image: Visual Studio 2019

environment:
  EnableNuGetPackageRestore: true

configuration:
- Release
- Debug

platform: Any CPU

install:
  - cmd: git submodule update --init --recursive
  
build:
  parallel: true                             # enable MSBuild parallel builds
  verbosity: minimal                         # MSBuild verbosity level (quiet|minimal|normal|detailed)
before_build:
- cmd: nuget restore -Verbosity quiet

after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%\gitshort.txt
- cmd: set /P GITSHORT=<%TMP%\gitshort.txt
- set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%PLATFORM%-%CONFIGURATION%.7z"
- cmd: cd "DropWebP\bin\%CONFIGURATION%"
- cmd: 7z a %BUILD_ARCHIVE% * -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%
- cmd: cd ..\..\..\..
test: off