"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var store_1 = require("@/store");
var vue_1 = require("vue");
require("@/styles/settings.scss");
var App_vue_1 = require("@/App.vue");
var i18n_1 = require("@/plugins/i18n");
var vuetify_1 = require("@/plugins/vuetify");
var app = (0, vue_1.createApp)(App_vue_1.default);
app.use(i18n_1.default);
app.use(vuetify_1.default);
app.use(store_1.default);
app.mount('#app');
