"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file is auto-generated by the build system.
var meta = {
    version: '2.2.2',
    date: '2025-10-03T07:45:29.049Z',
};
exports.default = meta;
