import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '2.2.2',
  date: '2025-10-03T07:55:16.321Z',
};
export default meta;
