//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropWebP.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DropWebP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About DropWebP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Select Folder... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrowseFolderText {
            get {
                return ResourceManager.GetString("BrowseFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch convert images in the selected folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrowseFolderTooltip {
            get {
                return ResourceManager.GetString("BrowseFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion of {0} files is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompleteMessage {
            get {
                return ResourceManager.GetString("CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File conversion is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompleteMessageSingle {
            get {
                return ResourceManager.GetString("CompleteMessageSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigText {
            get {
                return ResourceManager.GetString("ConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert from Clipboard... (_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertFromClipboardText {
            get {
                return ResourceManager.GetString("ConvertFromClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert from File(s)... (_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertFromFileText {
            get {
                return ResourceManager.GetString("ConvertFromFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertingMessage {
            get {
                return ResourceManager.GetString("ConvertingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DarkModeText {
            get {
                return ResourceManager.GetString("DarkModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogCompleteText {
            get {
                return ResourceManager.GetString("DialogCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting WebP... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogConvertingText {
            get {
                return ResourceManager.GetString("DialogConvertingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogInitializingText {
            get {
                return ResourceManager.GetString("DialogInitializingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to convert {0} out of {1} files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailureMessage {
            get {
                return ResourceManager.GetString("FailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop image file(s) to convert WebP.
        ///You can also use CTRL + V to convert the image in the clipboard directly to WebP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore JPEG images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IgnoreJpegText {
            get {
                return ResourceManager.GetString("IgnoreJpegText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since JPEG images are originally compressed, compressing them with WebP may increase the capacity.
        ///You can skip the JPEG compression process by turning on this toggle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IgnoreJpegTooltip {
            get {
                return ResourceManager.GetString("IgnoreJpegTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep original image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeepOriginalText {
            get {
                return ResourceManager.GetString("KeepOriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on this toggle if you want to keep the unconverted image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeepOriginalTooltip {
            get {
                return ResourceManager.GetString("KeepOriginalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lossless に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LosslessText {
            get {
                return ResourceManager.GetString("LosslessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on this toggle for lossless compression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LosslessTooltip {
            get {
                return ResourceManager.GetString("LosslessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify when completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyCompleteText {
            get {
                return ResourceManager.GetString("NotifyCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A desktop notification is issued when the process is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyCompleteTooltip {
            get {
                return ResourceManager.GetString("NotifyCompleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QualityText {
            get {
                return ResourceManager.GetString("QualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the quality for lossy compression of images.
        ///95 is the recommended value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QualityTooltip {
            get {
                return ResourceManager.GetString("QualityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon vise {
            get {
                object obj = ResourceManager.GetObject("vise", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Visit Project site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VisitText {
            get {
                return ResourceManager.GetString("VisitText", resourceCulture);
            }
        }
    }
}
